#
# Makefile for radios with Richwave RTC6213N FM Tuner
#

radio-i2c-rtc6213n-v2-objs	:= radio-rtc6213n-i2c.o radio-rtc6213n-common.o
obj-$(CONFIG_I2C_RTC6213N_V2) += radio-i2c-rtc6213n-v2.o
obj-$(CONFIG_RADIO_RTC6213N)  += radio-rtc6213n-i2c.o radio-rtc6213n-common.o
