#
# Makefile for the TDMB FC8080 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= broadcast_fc8080_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= broadcast_fc8080.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= tdmb_tunerbbdrv_fc8080.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= bbm.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_bb.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_demux.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_i2c.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_isr.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_ppi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_spi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fc8080_tun.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fci_hal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fci_oal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fci_tun.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_FC8080)		+= fci_hpi.o