#
# Makefile for kernel SPMI framework.
#
ccflags-$(CONFIG_DEBUG_SPMI)	+= -DDEBUG

obj-$(CONFIG_SPMI)	+= spmi.o

obj-$(CONFIG_SPMI_MSM_PMIC_ARB)	+= spmi-pmic-arb.o

obj-$(CONFIG_VIRTSPMI_MSM_PMIC_ARB)	+= virtspmi-pmic-arb.o
