obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_EARJACK_DEBUGGER) += lge_earjack_debugger.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o
obj-$(CONFIG_LGE_PM) += lge_monitor_thermal.o
obj-$(CONFIG_LGE_PM_CABLE_DETECTION) += lge_cable_detection.o
obj-$(CONFIG_LGE_PM_SMPL_COUNTER) += lge_smpl_count.o
obj-$(CONFIG_LGE_PM_CHARGING_CONTROLLER) += lge_charging_controller.o
ifdef CONFIG_LGE_PM_CHARGING_SCENARIO_V18
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario_v18.o
else
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario.o
endif
obj-$(CONFIG_LGE_PM_UNIFIED_NODE) += lge_power_sysfs.o
obj-$(CONFIG_LGE_PM_PSEUDO_BATTERY) += lge_pseudo_batt.o
obj-$(CONFIG_LGE_QSDL_SUPPORT) += lge_qsdl.o
obj-$(CONFIG_MACH_LGE) += lge_gpio_debug.o lge_boost_bypass.o
obj-$(CONFIG_LGE_ACC_NT) += lge_acc_nt.o
obj-$(CONFIG_LGE_LCD_TUNING) += lge_lcd_misc_ctrl.o
obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_PRE_SELF_DIAGNOSIS) += lge_pre_selfd.o
obj-$(CONFIG_LGE_PM_SUPPORT_LG_POWER_CLASS) += power/
obj-$(CONFIG_LGE_PKM) += lge_pkm_drv.o
