obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_PM) += lge_batt_detection.o
obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_LCD_TUNING) += lge_lcd_misc_ctrl.o
obj-$(CONFIG_LGE_IRRC) += lge_uei_irrc.o
